strategy:
  type: copy
  volume_ratio: 0.1
  target:
    driver: rubykube
    market: 'BTCUSD'
    host: "http://api.wb.local"
    key: ""
    secret: ""
    rate_limit: 1
  sources:
#    - driver: bitfaker
#      market: 'BTCUSDT'
#      host: "api.bitfinex.com"
#      key: ""
#      secret: ""
#      rate_limit: 0.2
#    - driver: bitfinex
#      market: 'BTCUSDT'
#      host: "api.bitfinex.com"
#      key: ""
#      secret: ""
#      rate_limit: 0.2
    - driver: binance
      market: 'BTCUSDT'
      host: "api.binance.com"
      key: ""
      secret: ""
      rate_limit: 0.2
